export const SampleMovements = [
  {name: "Explore All Movements!",
  description: "Check out the page with a collection of everyone's thoughts on all social movements!",
  url:""},
  {name: "The Black Lives Matter Social Movement",
  description: "It is hard to find anything that has marked the last two years in terms of social importance. The Black Lives Matter (BLM) movement has captured the entire world because the issues of racial prejudice are relevant as ever. In terms of possible topics, you can compare the BLM movement with the student protests in the 1970s or the Montgomery Bus Station protest",
  url:""},
  {name: "Climate Action",
  description: "On the list of social work’s Great Challenges, it might be surprising to see “strengthen social responses to environmental changes.” The effects of climate change can be seen all over the news from wildfires in Australia to record-breaking temps in the Arctic (one recent paper found that polar bears could be nearly extinct by the end of this century). This might seem like a problem for scientists, not social workers, but climate change can put a strain on resources and impact the wellbeing of entire communities. In reality, addressing climate justice can positively affect many of the other issues on this list, and social workers have the network and skills to mobilize and educate others on its impact.",
  url: ""},
  {name: "Refuge Crisis",
  description: "It dominated headlines in 2019, and it still remains a critical issue for those directly impacted. According to the United Nations, more people than ever before live in a different country than the one where they were born. Roughly 70.8 million people have been forced from their homes. Nearly 30 million of them are refugees, and more than half of the globe’s refugees are under 18 years old. This displaced population faces the challenges of accessing education, healthcare, job opportunities and other resources. Whether it’s escaping conflict in their home country or a natural disaster, refugees need additional support dealing with the logistical, mental and emotional burdens of their situation—support that social workers are uniquely adept at providing.",
  url: ""},
  {name: "Global Pandemic & Vaccination",
  description: "The subject of vaccination might be among the most discussed social issues today, yet it does not make it to the lists of immediate issues because of the political games at play. For example, you can write about unequal distributions of vaccines to certain countries and the ways how politics manipulate this sensitive matter.",
  url:""},
  {},
  {},
  {},
  {}
]